import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useMemo, useState } from "react";
import Header from "../components/Header";
import IconPanel from "../components/IconPanel";
import featherJson from "../data/feather.json";
import bootstrapJson from "../data/bootstap.json";
import { useLS } from "../hooks/useLS";

export type Icon = {
  name: string;
  tags: string[];
  svg: string;
};

const Home: NextPage = () => {
  const [icons, setIcons] = useState<Icon[]>([]);
  const [icon, setIcon] = useState<Icon | null>(null);
  const [search, setSearch] = useLS("search", "");

  useEffect(() => {
    setIcons(bootstrapJson as unknown as Icon[]);
  }, []);

  const filteredIcons = useMemo(() => {
    return icons.filter(({ name }) => name.includes(search.toLowerCase()));
  }, [icons, search]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header search={search} setSearch={setSearch} />
      <main className="pt-20 p-4 gap-4">
        <IconPanel icon={icon} reset={() => setIcon(null)} />
        <div
          className="grid gap-4 pl-80"
          style={{
            gridTemplateColumns: "repeat(auto-fill, minmax(60px ,1fr))",
          }}
        >
          {filteredIcons.map((icon, i) => (
            <div
              onClick={() => setIcon(icon)}
              key={i}
              dangerouslySetInnerHTML={{ __html: icon.svg }}
              className="aspect-square hover:border hover:bg-slate-200 cursor-pointer bg-slate-100 flex items-center justify-center rounded "
            ></div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
